services:
  web:
    image: node:22
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true